project_id = "cfsyxrokdemwkklqflnb"

[functions.process-car-image]
verify_jwt = false

[functions.analyze-scene]
verify_jwt = false

[functions.auto-crop-image]
verify_jwt = false

[functions.upload-scene-images]
verify_jwt = false
